
eureka:
  client:
    serviceUrl:
      #      eureka的注册中心地址
      defaultZone: http://localhost:8888/eureka/
server:
  #  此项目端口号
  port: 8887
spring:
  application:
    name: member-server
#    注册进eureka的名字
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            # 线程超时10秒,调用Fallback方法
            timeoutInMilliseconds: 1000

